# Generated by Django 4.1 on 2022-10-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='eventId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
