# Generated by Django 4.1 on 2022-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_like_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
